version: "3.9"
services:
    mysql-database:
        image: mysql
        container_name: mysql-container
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_ROOT_PASSWORD: "123456"
            MYSQL_DATABASE: "database_project"
        volumes: 
            - "./database/mysql:/var/lib/mysql"
        restart: always
        ports: 
            - "3306:3306"
    nodejs:
        build: "./"
        container_name: nodejs-container
        ports: 
            - "3030:3030"
        restart: always
        volumes: 
            - "./:/usr/app"
        depends_on:
            - mysql-database
